<?php
/*
include 'classes/communication.class.php';
include 'classes/meetings.class.php';
include 'classes/userDetails.class.php';

$stu_id = 1; //$_SESSION['user_id']

$c = new Communication ();
if ($_POST['communication_action']){
    try { $c->insert (); }
    catch (Exception $e){
        echo $e->getMessage ();
        return false;
    }
    echo $c->getResponse ();
}
$c->getAll('blog', $stu_id);
$blogs = $c->getResponse ();
$blog_count = count ($blogs);

$c->getAll('message', $stu_id);
$messages =  $c->getResponse ();
$message_count = count ($messages);

$m = new Meeting ();
if ($_POST['meeting_action']){
    try { $m->insert (); }
    catch (Exception $e){
        echo $e->getMessage ();
        return false;
    }
    echo $c->getResponse ();
}
// Vars returned from $c->getRespone ()
// Success message generated by class. Always a success message. Errors handled by try {} catch
$m->getAll(null, $stu_id);
$meetings =  $m->getResponse ();
$meeting_count = count ($meetings);

$u = new UserDetails ();
$u->studentSuper($stu_id); // (1) = demo student id
$supervisor = $u->getResponse ();
// Vars returned from getRespone ()
// $supervisor[0]['staff_first'] = Supervisor first name
// $supervisor[0]['staff_last'] = Supervisor last name
// $supervisor[0]['staff_id'] = Supervisor DB id
*/
?>

<!DOCTYPE html>
<html>

<head>
    <title>Communication</title>
    <link href="../css/styles.css" rel="stylesheet" type="text/css"/>
    <link type="text/css" rel="stylesheet" href="../css/materialize.min.css" media="screen,projection"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="../js/materialize.min.js"></script>
    <script>
        function toggleForm(elemID, newButtonID) {
            $(elemID).toggle();
            $(newButtonID).toggle();
        }
        ;

        $(document).ready(function () {
            $(".button-collapse").sideNav();
        });
    </script>
</head>
<body>
<nav>
    <div class="nav-wrapper green">
        <ul id="nav-mobile" class="side-nav">
            <li>
                <a href="index.php">Dashboard</a>
            </li>
            <li>
                <a href="meetings.php">Meetings</a>
            </li>
            <li>
                <a href="messages.php">Messages</a>
            </li>
            <li>
                <a href="blogs.php">Blog</a>
            </li>
            <li>
                <a href="uploads.php">Uploads</a>
            </li>
        </ul>
        <a class="button-collapse" href="#" data-activates="nav-mobile"><i class="mdi-navigation-menu"></i></a>
    </div>
</nav>

<div class="container">
    <div class="row">
        <h5 class="center-align">eSupervision Dashboard</h5>

        <!-- SUPERVISOR/SECOND MARKER -->
            <span class="col s10 offset-s1 m6 c_left-align">
                       Supervisor: <?php echo $supervisor[0]['staff_first'] . ' ' . $supervisor[0]['staff_last']; ?>
            </span>
            <span
                class="col s10 offset-s1 m6 c_right-align">Second Marker:<?php echo $supervisor[0]['staff_first'] . ' ' . $supervisor[0]['staff_last']; ?>
            </span>
    </div>

    <!-- MESSAGE SECTION START-->
    <div id="sendMessage" class="row">
        <i class="small mdi-content-clear c_right-align" onClick="toggleForm('#sendMessage', '#newMessage');"></i>

        <form id='communication' action='' method='POST' enctype="multipart/form-data" class="col s10 m12 offset-s1">
            <input type='hidden' name='communication_action' value='sendmessage'/>
            <input type='hidden' name='communication_from_id' value='1'/>
            <input type='hidden' name='communication_to_id' value='<?php echo $supervisor[0][' staff_id ']; ?>'/>
            <input type='hidden' name='communication_type_id' value='2'/>

            <div class="input-field">
                <textarea class="materialize-textarea" name='communication_body'></textarea>
                <label>New Message</label>
            </div>
            <input class="waves-effect waves-teal waves-light btn-flat" type="file" name="fileToUpload"
                   id="fileToUpload">
            <button class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">Submit</button>
        </form>
    </div>

    <div class="col s10 m12 offset-s1 card">
        <a onClick="toggleForm('#sendMessage', '#newMessage');" class="c_right_align" id="newMessage">
            <div class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">New Message</div>
        </a>

        <div class="card-content">
            <span class="card-title green-text">Message History</span>

            <p class="green-text">You have submitted
                <?php echo $message_count; ?> Message posts</p>
            <ul class="collection">
                <?php foreach ($messages as $m) {
                    echo '<li class="collection-item">';
                    echo $m['communication_body'];
                    echo "</li>";
                } ?>
            </ul>
        </div>
    </div>
    <!--MESSAGING SECTION END-->

    <!-- BLOG SECTION START -->
    <div id="submitBlog" class="row">
        <i class="small mdi-content-clear c_right-align" onClick="toggleForm('#submitBlog', '#newBlogEntry');"></i>

        <form name="blogEntry" method="post" action='' enctype="multipart/form-data" class="col s10 m12 offset-s1">
            <input type='hidden' name='communication_action' value='posttoblog'/>
            <input type='hidden' name='communication_from_id' value='1'/>
            <input type='hidden' name='communication_from_id' value='1'/>

            <div class="input-field">
                <textarea class="materialize-textarea" name='communication_body'></textarea>
                <label>New Blog Entry</label>
            </div>
            <button class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">Submit</button>
        </form>
    </div>
    <div class="col s10 m12 offset-s1 card">
        <a onClick="toggleForm('#submitBlog', '#newBlogEntry');" id="newBlogEntry" class="c_right-align">
            <div class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">New Entry</div>
        </a>

        <div class="card-content">
            <span class="card-title green-text">Blog History</span>

            <p class="green-text">You have submitted
                <?php echo $blog_count; ?> Blog posts</p>
            <ul class="collection">
                <?php foreach ($blogs as $b) {
                    echo '<li class="collection-item">';
                    echo $b['communication_body'];
                    echo "</li>";
                } ?>
            </ul>
        </div>
    </div>

    <!-- BLOG SECTION END -->

    <!-- MEETING SECTION START -->
    <div id="requestMeeting" class="row">
        <i class="small mdi-content-clear c_right-align" onClick="toggleForm('#requestMeeting', '#newMeeting');"></i>

        <form name='meetingRecord' action='' method='POST' enctype="multipart/form-data" class="col s10 m12 offset-s1">
            <input type='hidden' name='meeting_action' value='request'/>
            <input type='hidden' name='meeting_from_id' value='<?php echo $stu_id; ?>'/>
            <input type='hidden' name='meeting_to_id' value='<?php echo $supervisor[0][' staff_id ']; ?>'/>

            <div class="input-field">
                <textarea name='communication_body' class="materialize-textarea"></textarea>
                <label>Request a meeting</label>
            </div>
            <input class="waves-effect waves-teal waves-light btn-flat" type="file" name="fileToUpload"
                   id="fileToUpload">
            <button class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">Submit</button>
        </form>
    </div>

    <div class="col s10 m12 offset-s1 card">
        <a onClick="toggleForm('#requestMeeting', '#newMeeting');" class="c_right_align" id="newMeeting">
            <div class="c_right-align waves-effect waves-teal waves-light green btn-flat white-text">Request a Meeting
            </div>
        </a>

        <div class="card-content">
            <span class="card-title green-text">Meetings History</span>

            <p class="green-text">You have submitted
                <?php echo $meeting_count; ?> Meeting records</p>
            <ul class="collection">
                <?php foreach ($meetings as $mg) {
                    echo '<li class="collection-item" >';
                    echo $mg['meeting_title'];
                    echo "</li>";
                } ?>
            </ul>
        </div>
    </div>
    <!-- MEETING SECTION END -->
</div>
</body>
</html>